esphome:
  name: esp-omnik
  project:
    name: vsmeets.esphome-ens
    version: 1.0.0

external_components:
  - source:
      type: local
      path: components

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_ap_password

captive_portal:

uart:
  - id: RxLogger
    baud_rate: 9600
    rx_pin: D6
  - id: RxInverter
    baud_rate: 9600
    rx_pin: D7

omnik_logger:
  uart_id: RxLogger

omnik_inverter:
  uart_id: RxInverter
